### PR TITLE
udpate readme to fix possible typo

### PR DESCRIPTION
**Pull request by glihm**
Hello @Timmoth,

thank you for this useful resource. I wasn't able to do what I wanted with `LibMan`, using your approach looks very intuitive and flexible to me.

I pushed this pull request because I had trouble running your code from `README.md` on Windows with the double `@`. I am not an `npm` expert, but I supposed it was a typo.

If not, please apologize.

### CODE REVIEW

**Comment by Timmoth** [comment]
Thanks for the PR! 

I should really upload my new approach using webpack 'experimental' modules, its nice because you don't need the additional step of defining your exports twice!

**Comment by glihm** [comment]
That would be awesome! :) Thanks again @Timmoth.

**Comment by Timmoth** [comment]
@glihm Its a little rough but here you go! 
https://timmoth.com/posts/-Su82EIepEmRKk1usEBA5w
https://github.com/Timmoth/npm-webpack-blazor

**Comment by glihm** [comment]
Works so nicely... Very elegant, I am loving it! (I posted some messages on your website chat, but not sure if it worked ^^).
Thanks again @Timmoth!

**Pull request merged**
